version: '3'

services:
  eureka-server:
    image: localhost:5000/eureka-server:latest
    ports:
      - "8761:8761"
  billing:
    image: localhost:5000/billing-service:latest
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
  customers:
    image: localhost:5000/customers-service:latest
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
  products:
    image: localhost:5000/products-service:latest
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
  gateway:
    image: localhost:5000/gateway-service:latest
    ports:
      - "8888:80"
    depends_on:
      - eureka-server
